apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lpoawsn5v-go
  janus-idp.io/tekton: lpoawsn5v-go
  backstage.io/kubernetes-id: lpoawsn5v-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lpoawsn5v-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
