apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: lpoawsn5v-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:b06680b499dc1c93c531a1eedb98b71a2ed3c930@sha256:6302ff209cd8f288ddb3d2cf27c16552a4f603e2b86aefd022df5def7668158c
          name: container-image
